CREATE SCHEMA IF NOT EXISTS trainingLibrary DEFAULT CHARACTER SET utf8 ;
USE trainingLibrary;

CREATE TABLE IF NOT EXISTS trainings (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB;
