spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        package-scan: trainingLibrary
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/trainingLibrary
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase-changeLog.xml
